import type { OcrDebugPass, OcrDebugSnapshot } from './receiptScanner';

const element = <K extends keyof HTMLElementTagNameMap>(tag:K,className?:string,text?:string) => { const node=document.createElement(tag); if(className)node.className=className;if(text!==undefined)node.textContent=text;return node; };
function imageCard(title:string,url:string){const card=element('section','ocr-debug-card'),heading=element('h3','',title),image=element('img') as HTMLImageElement;image.src=url;image.alt=title;card.append(heading,image);return card;}
function overlayCard(pass:OcrDebugPass,url:string){const card=element('section','ocr-debug-card'),heading=element('h3','',`${pass.mode} · OCR bounding boxes`),stage=element('div','ocr-debug-overlay'),image=element('img') as HTMLImageElement,svg=document.createElementNS('http://www.w3.org/2000/svg','svg');image.src=url;image.alt='Receipt with OCR word bounding boxes';const width=pass.imageWidth||Math.max(1,...pass.words.map(word=>word.x+word.width)),height=pass.imageHeight||Math.max(1,...pass.words.map(word=>word.y+word.height));svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('aria-label','OCR bounding boxes');for(const word of pass.words){const rect=document.createElementNS(svg.namespaceURI,'rect'),title=document.createElementNS(svg.namespaceURI,'title');rect.setAttribute('x',String(word.x));rect.setAttribute('y',String(word.y));rect.setAttribute('width',String(word.width));rect.setAttribute('height',String(word.height));rect.setAttribute('class',word.confidence<60?'low':'');title.textContent=`${word.text} · ${word.confidence.toFixed(1)}% · x:${word.x} y:${word.y} w:${word.width} h:${word.height}`;rect.append(title);svg.append(rect);}stage.append(image,svg);card.append(heading,stage);return card;}
function rawTextCard(pass:OcrDebugPass){const card=element('section','ocr-debug-card'),pre=element('pre','ocr-debug-raw');pre.textContent=pass.rawText;card.append(element('h3','',`${pass.mode} · raw OCR text (unmodified)`),pre);return card;}
function tokenCard(pass:OcrDebugPass){const card=element('section','ocr-debug-card'),wrap=element('div','ocr-debug-table-wrap'),table=element('table','ocr-debug-table'),head=document.createElement('thead'),body=document.createElement('tbody');head.innerHTML='<tr><th>text</th><th>confidence</th><th>x</th><th>y</th><th>width</th><th>height</th></tr>';for(const word of pass.words){const row=document.createElement('tr');for(const value of [word.text,word.confidence.toFixed(2),word.x,word.y,word.width,word.height])row.append(element('td','',String(value)));body.append(row);}table.append(head,body);wrap.append(table);card.append(element('h3','',`${pass.mode} · words/tokens (${pass.words.length})`),wrap);return card;}
function lineCard(pass:OcrDebugPass){const card=element('section','ocr-debug-card'),list=element('ol','ocr-debug-lines');pass.rows.forEach((row,index)=>{const item=element('li');item.append(element('code','',row.text),element('small','',`confidence ${row.confidence.toFixed(1)}% · ${pass.classifications[index]}`));list.append(item);});card.append(element('h3','',`${pass.mode} · reconstructed lines and columns`));if(pass.metrics)card.append(element('pre','ocr-debug-json',JSON.stringify(pass.metrics,null,2)));card.append(element('pre','ocr-debug-json',JSON.stringify(pass.columns,null,2)),list);return card;}

export function renderOcrDebugPanel(snapshot:OcrDebugSnapshot){const previous=document.getElementById('receipt-ocr-debug');previous?.remove();const panel=element('aside','ocr-debug-panel');panel.id='receipt-ocr-debug';panel.dataset.original=snapshot.originalImageUrl;panel.dataset.preprocessed=snapshot.preprocessedImageUrl;const header=element('header','ocr-debug-header'),title=element('div');title.append(element('strong','','Receipt OCR Debug Panel'),element('span','','Raw OCR → layout reconstruction → parser'));const close=element('button','ocr-debug-close','Close');close.type='button';close.onclick=()=>panel.remove();header.append(title,close);const content=element('div','ocr-debug-content'),images=element('div','ocr-debug-images');images.append(imageCard('1. Original receipt image',snapshot.originalImageUrl),imageCard('2. Legacy Tesseract preprocessed image',snapshot.preprocessedImageUrl));content.append(images);snapshot.passes.forEach(pass=>{content.append(overlayCard(pass,pass.imageSource==='original'?snapshot.originalImageUrl:snapshot.preprocessedImageUrl),rawTextCard(pass),tokenCard(pass),lineCard(pass));});const final=element('section','ocr-debug-card');final.append(element('h3','','Final parsed items'),element('pre','ocr-debug-json',JSON.stringify(snapshot.finalItems,null,2)));content.append(final);panel.append(header,content);document.body.append(panel);}
