import { beforeEach, describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { fixture } from './fixture';
let context:any, rows:any[][], triggers:any[];
const sessionA='fs_'+'a'.repeat(64), sessionB='fs_'+'b'.repeat(64);
beforeEach(()=>{vi.useRealTimers();rows=[];triggers=[];const sheet={getLastRow:()=>rows.length+1,getRange:(row?:number,column?:number,numRows?:number)=>numRows?{getValues:()=>rows.map(r=>[...r])}:{setValue:(value:unknown)=>{rows[row!-2][column!-1]=value;}},appendRow:(r:any[])=>rows.push(r),deleteRow:(n:number)=>rows.splice(n-2,1)};context=vm.createContext({Date,JSON,Math,Number,Set,BigInt,console,PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'test'})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet})},Utilities:{getUuid:()=>crypto.randomUUID()},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock:()=>{},releaseLock:()=>{}})},ScriptApp:{getProjectTriggers:()=>triggers,newTrigger:(name:string)=>({timeBased:()=>({everyHours:()=>({create:()=>triggers.push({getHandlerFunction:()=>name})})})})},ContentService:{MimeType:{JSON:'json'},createTextOutput:(s:string)=>({setMimeType:()=>JSON.parse(s)})}});vm.runInContext(readFileSync('google-apps-script/Code.gs','utf8'),context);});
describe('Apps Script persistence, ownership and expiration',()=>{
  it('creates, reads, deletes and rejects another session',()=>{const saved=context.createReceipt_(sessionA,fixture());expect(Date.parse(saved.expiresAt)-Date.parse(saved.createdAt)).toBe(72*3600000);expect(context.history_(sessionA)[0].id).toBe(saved.id);expect(()=>context.getReceipt_(sessionB,saved.id)).toThrow();expect(()=>context.deleteReceipt_(sessionB,saved.id)).toThrow();expect(context.deleteReceipt_(sessionA,saved.id)).toBe(true);});
  it('deduplicates request retries and recalculates forged totals',()=>{const bill=fixture();bill.totalCents=1;bill.settlements=[];const saved=context.createReceipt_(sessionA,bill);expect(saved.totalCents).toBe(1150);expect(context.createReceipt_(sessionA,bill).id).toBe(saved.id);expect(rows).toHaveLength(1);});
  it('updates payment without changing totals and rejects another session',()=>{const saved=context.createReceipt_(sessionA,fixture());const updated=context.updatePaymentStatus_(sessionA,saved.id,'a',true);expect(updated.paymentStatus.a).toBe(true);expect(updated.totalCents).toBe(1150);expect(updated.settlements.reduce((sum:number,p:any)=>sum+p.finalTotalCents,0)).toBe(1150);expect(()=>context.updatePaymentStatus_(sessionB,saved.id,'a',false)).toThrow();expect(()=>context.updatePaymentStatus_(sessionA,saved.id,'missing',true)).toThrow();});
  it('expires and cleans receipts at exactly 72 hours',()=>{const saved=context.createReceipt_(sessionA,fixture());context.Date=class extends Date{static now(){return Date.parse(saved.expiresAt);}};expect(context.history_(sessionA)).toHaveLength(0);expect(context.cleanupExpiredReceipts()).toBe(1);});
});
