import { beforeEach,describe,it,expect,vi } from 'vitest';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { fixture } from './fixture';
let context:any,rows:any[][],triggers:any[];
const sessionA='fs_'+'a'.repeat(64),sessionB='fs_'+'b'.repeat(64);
beforeEach(()=>{vi.useRealTimers();rows=[];triggers=[];const sheet={getLastRow:()=>rows.length+1,getRange:()=>({getValues:()=>rows.map(r=>[...r])}),appendRow:(r:any[])=>rows.push(r),deleteRow:(n:number)=>rows.splice(n-2,1)};context=vm.createContext({Date,JSON,Math,Number,Set,BigInt,console,PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'test'})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet})},Utilities:{getUuid:()=>crypto.randomUUID()},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock:()=>{},releaseLock:()=>{}})},ScriptApp:{getProjectTriggers:()=>triggers,newTrigger:(name:string)=>({timeBased:()=>({everyHours:()=>({create:()=>triggers.push({getHandlerFunction:()=>name})})})})},ContentService:{MimeType:{JSON:'json'},createTextOutput:(s:string)=>({setMimeType:()=>JSON.parse(s)})}});vm.runInContext(readFileSync('google-apps-script/Code.gs','utf8'),context);});
describe('Apps Script persistence, ownership and expiration',()=>{
  it('creates, reads history and details, then deletes',()=>{const saved=context.createReceipt_(sessionA,fixture());expect(rows).toHaveLength(1);expect(Date.parse(saved.expiresAt)-Date.parse(saved.createdAt)).toBe(72*3600000);expect(context.history_(sessionA)[0].id).toBe(saved.id);expect(context.getReceipt_(sessionA,saved.id).id).toBe(saved.id);expect(context.deleteReceipt_(sessionA,saved.id)).toBe(true);expect(context.history_(sessionA)).toHaveLength(0);});
  it('prevents another session reading or deleting a receipt',()=>{const saved=context.createReceipt_(sessionA,fixture());expect(context.history_(sessionB)).toHaveLength(0);expect(()=>context.getReceipt_(sessionB,saved.id)).toThrow();expect(()=>context.deleteReceipt_(sessionB,saved.id)).toThrow();expect(rows).toHaveLength(1);});
  it('filters at the exact 72-hour boundary and cleans expired rows',()=>{const saved=context.createReceipt_(sessionA,fixture());context.Date=class extends Date{static now(){return Date.parse(saved.expiresAt);}};expect(context.history_(sessionA)).toHaveLength(0);expect(()=>context.getReceipt_(sessionA,saved.id)).toThrow();expect(context.cleanupExpiredReceipts()).toBe(1);expect(context.cleanupExpiredReceipts()).toBe(0);});
  it('deduplicates retries and ignores forged totals / timestamps',()=>{const b=fixture();b.totalCents=1;b.createdAt='1900-01-01';b.settlements=[];const saved=context.createReceipt_(sessionA,b);expect(saved.totalCents).toBe(1150);expect(saved.settlements.reduce((s:number,p:any)=>s+p.finalTotalCents,0)).toBe(1150);expect(context.createReceipt_(sessionA,b).id).toBe(saved.id);expect(rows).toHaveLength(1);});
  it('rejects duplicate units, unassigned items, malformed sessions',()=>{const b=fixture();b.itemUnits.push(b.itemUnits[0]);expect(()=>context.createReceipt_(sessionA,b)).toThrow();const c=fixture();c.itemUnits[0].participantIds=[];expect(()=>context.createReceipt_(sessionA,c)).toThrow();expect(context.doPost({postData:{contents:JSON.stringify({action:'history',sessionId:'guess'})}}).ok).toBe(false);});
  it('escapes spreadsheet formulas while retaining original restaurant text',()=>{const b=fixture();b.restaurant='=1+1';context.createReceipt_(sessionA,b);expect(rows[0][2]).toBe("'=1+1");expect(JSON.parse(rows[0][11]).restaurant).toBe('=1+1');});
  it('does not create duplicate cleanup triggers',()=>{context.createCleanupTrigger();context.createCleanupTrigger();expect(triggers).toHaveLength(1);});
});
describe('Receipt scan parsing and amount reconciliation',()=>{
  const extracted=()=>({restaurant:"L'ARCHETTO DI CAVOUR",error:'',items:[{name:'Tovagliato',quantity:2,totalPriceCents:200},...['Birra Media','Acqua Minerale','Coca Cola','Lasagne','Piz Diavola'].map((name,n)=>({name,quantity:1,totalPriceCents:[600,250,350,1300,1100][n]}))],serviceChargeCents:0,taxCents:0,discountCents:0,receiptTotalCents:3800});
  it('preserves the sample receipt total and derives unit prices from line amounts',()=>{const r=context.normalizeScan_(extracted());expect(r.items[0].unitPriceCents).toBe(100);expect(r.items.reduce((s:number,i:any)=>s+i.totalPriceCents,0)).toBe(3800);expect(r.scanWarning).toBeUndefined();});
  it('warns on a mismatch without silently changing amounts',()=>{const raw=extracted();raw.receiptTotalCents=4000;const r=context.normalizeScan_(raw);expect(r.scanWarning).toContain('40.00');expect(r.items[0].totalPriceCents).toBe(200);});
  it('preserves indivisible line totals and quantity',()=>{const raw=extracted();raw.items=[{name:'Shared item',quantity:3,totalPriceCents:1000}];raw.receiptTotalCents=1000;const r=context.normalizeScan_(raw);expect(r.items.reduce((s:number,i:any)=>s+i.totalPriceCents,0)).toBe(1000);expect(r.items.reduce((s:number,i:any)=>s+i.quantity,0)).toBe(3);});
  it('reads multipart JSON while ignoring thought parts',()=>{const raw=extracted();const text=JSON.stringify(raw);expect(context.parseScanResponse_({candidates:[{finishReason:'STOP',content:{parts:[{text:'reasoning',thought:true},{text:text.slice(0,50)},{text:text.slice(50)}]}}]})).toEqual(raw);});
  it('distinguishes malformed and incomplete provider responses from image clarity',()=>{expect(()=>context.parseScanResponse_({candidates:[{finishReason:'MAX_TOKENS',content:{parts:[]}}]})).toThrow('complete');expect(()=>context.parseScanResponse_({candidates:[{content:{parts:[{text:'invalid'}]}}]})).toThrow('format');});
  it('reports configuration and provider quota failures accurately',()=>{context.PropertiesService={getScriptProperties:()=>({getProperty:()=>null})};expect(()=>context.scanReceipt_({})).toThrow('not connected');context.PropertiesService={getScriptProperties:()=>({getProperty:()=> 'test'})};context.CacheService={getScriptCache:()=>({get:()=>null,put:()=>{}})};context.UrlFetchApp={fetch:()=>({getResponseCode:()=>429})};expect(()=>context.scanReceipt_({mimeType:'image/png',image:'YWJj',sessionId:sessionA})).toThrow('quota');});
});
