import { describe, expect, it } from 'vitest';
import { itemsFromLayout, type OcrWord, type ReceiptLayout, type ReceiptRow } from '../src/receipt-malaysia/receiptLayout';

function makeLayout(lines:Array<Array<[string,number,number?]>>):ReceiptLayout { const rows:ReceiptRow[]=lines.map((line,index)=>{const words:OcrWord[]=line.map(([text,x,confidence=92])=>({text,x,y:index*30,width:Math.max(14,text.length*8),height:16,confidence}));return{words,text:words.map(word=>word.text).join(' '),confidence:words.reduce((sum,word)=>sum+word.confidence,0)/words.length,y:index*30};});const words=rows.flatMap(row=>row.words);return{words,rows,width:Math.max(...words.map(word=>word.x+word.width)),height:rows.length*30,text:rows.map(row=>row.text).join('\n')}; }

describe('layout-agnostic receipt item strategies',()=>{
  it('parses trailing-price rows without a header or quantity column',()=>{const items=itemsFromLayout(makeLayout([[['Chicken',80],['Rice',150],['8.50',520]],[['Coke',80],['3.00',520]],[['TOTAL',80],['11.50',520]]]));expect(items.map(item=>[item.name,item.quantity,item.totalPriceCents])).toEqual([['Chicken Rice',1,850],['Coke',1,300]]);});
  it('uses a repeated middle quantity column dynamically',()=>{const items=itemsFromLayout(makeLayout([[['ITEM',50],['QTY',350],['AMT',520]],[['Chicken',50],['Rice',120],['2',350],['17.00',520]]]));expect(items[0]).toMatchObject({name:'Chicken Rice',quantity:2,unitPriceCents:850,totalPriceCents:1700});});
  it('merges a multiline mixed-language description with its nearby price',()=>{const items=itemsFromLayout(makeLayout([[['B4',80],['Teh',120],['红茶加冻奶',170]],[['(Hot',100],['热)',150],['(Small)',190]],[['2.20',520]],[['TOTAL',80],['2.20',520]]]));expect(items[0]).toMatchObject({name:'B4 Teh 红茶加冻奶 (Hot 热) (Small)',totalPriceCents:220});});
  it('understands quantity, unit price and total on separate rows',()=>{const items=itemsFromLayout(makeLayout([[['Chicken',80],['Rice',150]],[['Qty',80],['2',150]],[['Unit',80],['8.50',520]],[['Total',80],['17.00',520]]]));expect(items[0]).toMatchObject({name:'Chicken Rice',quantity:2,unitPriceCents:850,totalPriceCents:1700});});
  it('uses explicit at-price math when no line total is printed',()=>{const items=itemsFromLayout(makeLayout([[['2',50],['Nasi',100],['Lemak',160],['@',300],['8.50',520]]]));expect(items[0]).toMatchObject({name:'Nasi Lemak',quantity:2,unitPriceCents:850,totalPriceCents:1700});});
  it('keeps priced add-ons as editable items',()=>{const items=itemsFromLayout(makeLayout([[['Chicken',80],['Rice',150],['8.50',520]],[['Add',110],['Egg',160],['1.50',520]]]));expect(items.map(item=>item.name)).toEqual(['Chicken Rice','Add Egg']);});
  it('ignores a supermarket barcode before an unknown product layout',()=>{const items=itemsFromLayout(makeLayout([[['9551234567890',60]],[['UNKNOWN',80],['PRODUCT',170]],[['4.50',520]],[['TOTAL',80],['4.50',520]]]));expect(items[0]).toMatchObject({name:'UNKNOWN PRODUCT',totalPriceCents:450});});
  it('marks mathematically inconsistent interpretations for review',()=>{const items=itemsFromLayout(makeLayout([[['QTY',30],['ITEM',100],['PRICE',400],['TOTAL',520]],[['3',30],['Coffee',100],['4.50',400],['135.00',520]]]));expect(items[0]).toMatchObject({quantity:3,unitPriceCents:450,totalPriceCents:13500,needsReview:true});});
});
