import { describe, it, expect } from 'vitest';
import { parseReceiptText, parseReceiptTsv, prepareReceiptImage, receiptRowsFromTsv, validateReceiptImage } from '../src/services/receiptScanner';
describe('Receipt image input',()=>{
  it('accepts large supported photos for preprocessing',()=>{expect(()=>validateReceiptImage(new File([new Uint8Array(5*1024*1024)],'receipt.jpg',{type:'image/jpeg'}))).not.toThrow();});
  it('keeps small images unchanged to preserve fine print',async()=>{const file=new File(['image'],'receipt.png',{type:'image/png'});expect(await prepareReceiptImage(file)).toBe(file);});
  it('gives actionable errors for unsupported and empty photos',()=>{expect(()=>validateReceiptImage(new File(['image'],'receipt.heic',{type:'image/heic'}))).toThrow('export as JPG');expect(()=>validateReceiptImage(new File([],'receipt.png',{type:'image/png'}))).toThrow('empty');});
  it('reconstructs item rows from sparse OCR coordinates',()=>{const header='level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext';const words=['5\t1\t1\t1\t1\t1\t100\t100\t30\t16\t90\tTeh','5\t1\t2\t1\t1\t1\t140\t102\t20\t16\t90\tO','5\t1\t3\t1\t1\t1\t450\t99\t35\t16\t95\t3.00','5\t1\t4\t1\t1\t1\t620\t105\t35\t16\t95\t3.00','5\t1\t5\t1\t1\t1\t100\t135\t40\t16\t90\tRoti','5\t1\t6\t1\t1\t1\t150\t136\t40\t16\t90\tTelur','5\t1\t7\t1\t1\t1\t620\t140\t35\t16\t95\t3.40'];expect(receiptRowsFromTsv([header,...words].join('\n'))).toBe('Teh O 3.00 3.00\nRoti Telur 3.40');});
  it('uses X columns, confidence and quantity math after Y-row reconstruction',()=>{const header='level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext',word=(block:number,x:number,y:number,confidence:number,text:string)=>`5\t1\t${block}\t1\t1\t1\t${x}\t${y}\t40\t16\t${confidence}\t${text}`,tsv=[header,word(1,10,10,95,'QTY'),word(2,100,10,95,'DESCRIPTION'),word(3,400,10,95,'PRICE'),word(4,500,10,95,'TOTAL'),word(5,10,40,45,'2'),word(6,100,40,45,'Cheese'),word(7,160,40,45,'Toast'),word(8,400,40,45,'3.00'),word(9,500,40,45,'6.00'),word(10,100,80,95,'TOTAL'),word(11,500,80,95,'6.00')].join('\n'),receipt=parseReceiptTsv(tsv);expect(receipt.items[0]).toMatchObject({name:'Cheese Toast',quantity:2,unitPriceCents:300,totalPriceCents:600,needsReview:true});expect(receipt.items[0].confidence).toBeCloseTo(.45);});
  it('parses Malaysian service tax, service charge, Malay labels and QR payment without treating them as food',()=>{const receipt=parseReceiptText('Kedai Makan Harmoni\n2 x Nasi Lemak RM 8.50 17.00\nTeh Tarik RM 3.20\nCaj Perkhidmatan 10% 2.02\nCukai Perkhidmatan 6% 1.21\nDiskaun Member -1.00\nJUMLAH PERLU DIBAYAR RM 22.43\nDuitNow QR 22.43');expect(receipt.items.map(i=>i.name)).toEqual(['Nasi Lemak','Teh Tarik']);expect(receipt.serviceChargeCents).toBe(202);expect(receipt.taxCents).toBe(121);expect(receipt.discountCents).toBe(100);});
  it('does not infer tax from a GST ID or GST column when the receipt says Total GST 0.00',()=>{const receipt=parseReceiptText('CHOCOLICIOUS SDN BHD\nGST ID : 0014632550040\nCINNAMON CRUNCHY 30.00\nTotal Sales (Excluding GST) : 62.40\nDiscount : 3.00\nTotal GST : 0.00\nTotal Sales (Inclusive of GST) : 59.40\nCASH : 60.40\nChange : 1.00');expect(receipt.items.map(i=>i.name)).toEqual(['CINNAMON CRUNCHY']);expect(receipt.taxCents).toBe(0);expect(receipt.discountCents).toBe(300);});
  it('handles supermarket barcodes, weighted products, delivery fees and contextual OCR money fixes',()=>{const receipt=parseReceiptText('MYGROCER\n9551234567890\nAPPLE\n0.650 KG x 8.90 5.79\nNASI LEMAK 8.SO\nDelivery Fee 3.00\nTOTAL 17.29');expect(receipt.items.map(i=>i.name)).toEqual(['APPLE','NASI LEMAK']);expect(receipt.items.map(i=>i.totalPriceCents)).toEqual([579,850]);expect(receipt.serviceChargeCents).toBe(300);});
});
describe('local receipt parser',()=>{
  it('understands Qty/Item/Price and /ea semantics on a mixed-language restaurant POS receipt',()=>{const receipt=parseReceiptText('WOK IN CAFE\nREGISTRATION NO: TR0268788-V\nInvoice no: 36198\nDate: 10/09/2026 21:54\nTable Pax: 1\nORDER\nC63\nQty Item Price (MYR)\n1 Custom Item (3.00/ea) 3.00\n1 B4 Teh 红茶加冻奶 (Hot 热 (Small)) 2.20\n(2.20/ea)\n1 Cheese Toast 烤芝士面包 (3.00/ea) 3.00\n1 O5 PLAIN WATER (0.50/ea) 0.50\n4 Qty\nSubtotal 8.70\nBill rounding 0.00\nTotal (MYR) 8.70\nBalance 8.70');expect(receipt.restaurant).toBe('WOK IN CAFE');expect(receipt.items.map(i=>({name:i.name,quantity:i.quantity,unit:i.unitPriceCents,total:i.totalPriceCents}))).toEqual([{name:'Custom Item',quantity:1,unit:300,total:300},{name:'B4 Teh 红茶加冻奶 (Hot 热 (Small))',quantity:1,unit:220,total:220},{name:'Cheese Toast 烤芝士面包',quantity:1,unit:300,total:300},{name:'O5 PLAIN WATER',quantity:1,unit:50,total:50}]);expect(receipt.scanWarning).not.toContain('while the printed total');});
  it('uses line total rather than /ea unit price for multiple quantities',()=>{const receipt=parseReceiptText('CAFE TEST\nQty Item Price\n2 Cheese Toast (3.00/ea) 6.00\n2 Qty\nSubtotal 6.00\nTotal 6.00');expect(receipt.items[0]).toMatchObject({name:'Cheese Toast',quantity:2,unitPriceCents:300,totalPriceCents:600});});
  it('extracts Malaysian-style item amounts and charges conservatively',()=>{const receipt=parseReceiptText('Kedai Makan\nChicken Rice RM 8.50\n2 x Coke 6.00\nService Charge 1.45\nSST 0.87\nTotal 16.82');expect(receipt.restaurant).toBe('Kedai Makan');expect(receipt.items.map(i=>i.name)).toEqual(['Chicken Rice','Coke']);expect(receipt.items[1].quantity).toBe(2);expect(receipt.serviceChargeCents).toBe(145);expect(receipt.taxCents).toBe(87);});
  it('does not manufacture unreadable item lines',()=>{expect(parseReceiptText('TOTAL RM 10.00').items).toEqual([]);});
  it('does not treat subtotal or TNG settlement lines as food',()=>{const receipt=parseReceiptText('Mango Juice 6.50\nCreme Brulee Souffle Pancake 17.90\nEe SUBTTL 24.40\nBee TNG 28.30');expect(receipt.items.map(i=>i.name)).toEqual(['Mango Juice','Creme Brulee Souffle Pancake']);});
  it('excludes Italian and Chinese subtotal and payment rows',()=>{const receipt=parseReceiptText('2x Tovagliato 2,00\n1x Birra Media 6,00\nSUBTOTALE 8,00\nTOTALE EUR 8,00\n清炒白菜 28.00\n小计 28.00\n实收 28.00');expect(receipt.items.map(i=>i.name)).toEqual(['Tovagliato','Birra Media','清炒白菜']);});
  it('does not extract a price from identifiers or total-GST rows',()=>{const receipt=parseReceiptText('LOT TL 1.108.00\nChocolate 30.00\nTotalGST 0.00\nTotal Sales 30.00');expect(receipt.items.map(i=>i.name)).toEqual(['Chocolate']);});
  it('recognizes spaced Chinese labels and table quantities',()=>{const receipt=parseReceiptText('矿 泉 水 6 3.00 18.00\n应 收 452.00\n优 惠 20.00\n实 收 432.00');expect(receipt.items.map(i=>({name:i.name,quantity:i.quantity,total:i.totalPriceCents}))).toEqual([{name:'矿 泉 水',quantity:6,total:1800}]);expect(receipt.discountCents).toBe(2000);});
  it('recognizes quantity-at-price and quantity-first receipt columns',()=>{const receipt=parseReceiptText('PLAIN NAAN 11.0 @ 3.00 33.00\n2 Grilled chicken sandwich 8.50 17.00');expect(receipt.items.map(i=>({name:i.name,quantity:i.quantity,total:i.totalPriceCents}))).toEqual([{name:'PLAIN NAAN',quantity:11,total:3300},{name:'Grilled chicken sandwich',quantity:2,total:1700}]);});
});
