import {useMemo,useRef,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Plus,Trash2,X} from 'lucide-react';
import type {OcrToken,Receipt,ReceiptAssignment,ReceiptField} from '../types';
import {ReceiptViewer} from './ReceiptViewer';

const ITEM:[ReceiptField,string][]=[['itemName','Food name'],['quantity','Quantity'],['unitPrice','Unit price'],['itemTotal','Item total']];
// Subtotal is derived from item rows and is no longer a user input.
const CHARGE:[ReceiptField,string][]=[['serviceCharge','Service tax / charge'],['tax','GST / SST'],['discount','Discount'],['rounding','Rounding']];
const toCents=(value:string)=>Math.round((Number(value.replace(/[^0-9.-]/g,''))||0)*100);
type Target={field:ReceiptField;item?:number;label:string};

export function ReceiptMapper({imageUrl,imageWidth,imageHeight,tokens,initial,initialAssignments=[],onConfirm,onClear,onClose,onExport}:{imageUrl:string;imageWidth:number;imageHeight:number;tokens:OcrToken[];initial:Receipt;initialAssignments?:ReceiptAssignment[];onConfirm:(receipt:Receipt,assignments:ReceiptAssignment[])=>void;onClear:()=>void;onClose:()=>void;onExport?:()=>void}){
  const [items,setItems]=useState(initial.items.length?initial.items:[{id:crypto.randomUUID(),name:'',quantity:1,unitPriceCents:0,totalPriceCents:0}]);
  const [restaurant,setRestaurant]=useState(initial.restaurant);
  const [charges,setCharges]=useState({serviceCharge:initial.serviceChargeCents,tax:initial.taxCents,discount:initial.discountCents,rounding:initial.roundingCents||0});
  const [card,setCard]=useState(0),[active,setActive]=useState<Target>({field:'itemName',item:0,label:'Food name'}),[selected,setSelected]=useState<string[]>([]),[assignments,setAssignments]=useState<ReceiptAssignment[]>(initialAssignments),[auto,setAuto]=useState(true);
  const workspace=useRef<HTMLDivElement>(null),swipe=useRef<number|null>(null);
  const used=new Set(assignments.flatMap(assignment=>assignment.tokenIds));
  const ordered=useMemo(()=>[...selected].sort((leftId,rightId)=>{const left=tokens.find(token=>token.id===leftId)!,right=tokens.find(token=>token.id===rightId)!;return left.bbox.y-right.bbox.y||left.bbox.x-right.bbox.x;}),[selected,tokens]);
  const selectedText=ordered.map(id=>tokens.find(token=>token.id===id)?.text||'').join(' '),last=items.length;
  const calculatedSubtotal=items.reduce((sum,item)=>sum+item.totalPriceCents,0);
  const calculatedTotal=calculatedSubtotal+charges.serviceCharge+charges.tax+charges.rounding-charges.discount;

  const setItem=(index:number,field:ReceiptField,value:string)=>setItems(current=>current.map((item,itemIndex)=>{
    if(itemIndex!==index)return item;
    if(field==='itemName')return {...item,name:value};
    if(field==='quantity'){const quantity=Math.max(1,Number.parseInt(value.replace(/\D/g,''),10)||1);return {...item,quantity,totalPriceCents:quantity*item.unitPriceCents};}
    if(field==='unitPrice'){const unitPriceCents=toCents(value);return {...item,unitPriceCents,totalPriceCents:item.quantity*unitPriceCents};}
    const totalPriceCents=toCents(value);return {...item,totalPriceCents,unitPriceCents:item.quantity>0?Math.round(totalPriceCents/item.quantity):totalPriceCents};
  }));
  const activate=(target:Target)=>{setActive(target);setSelected([])};
  const advance=(target:Target)=>{if(!auto)return;if(target.item!==undefined){const fieldIndex=ITEM.findIndex(([field])=>field===target.field);if(fieldIndex<ITEM.length-1){const [field,label]=ITEM[fieldIndex+1];setActive({field,label,item:target.item});}else if(target.item<items.length-1){setCard(target.item+1);setActive({field:'itemName',label:'Food name',item:target.item+1});}else{setCard(last);setActive({field:'serviceCharge',label:'Service tax / charge'});}}};
  const assign=(target=active,ids=ordered)=>{if(!ids.length)return;const value=ids.map(id=>tokens.find(token=>token.id===id)?.text||'').join(' ');setAssignments(current=>[...current.filter(assignment=>assignment.field!==target.field||assignment.itemIndex!==target.item),{tokenIds:ids,field:target.field,itemIndex:target.item,correctedText:value}]);if(target.field==='restaurant')setRestaurant(value);else if(target.item!==undefined)setItem(target.item,target.field,value);else if(target.field in charges)setCharges(current=>({...current,[target.field]:toCents(value)}));setSelected([]);advance(target);};
  const tokenTap=(id:string)=>active.field==='itemName'?setSelected(current=>current.includes(id)?current.filter(selectedId=>selectedId!==id):[...current,id]):assign(active,[id]);
  const itemValue=(index:number,field:ReceiptField)=>{const item=items[index];return field==='itemName'?item.name:field==='quantity'?String(item.quantity):field==='unitPrice'?(item.unitPriceCents/100).toFixed(2):(item.totalPriceCents/100).toFixed(2)};
  const status=(field:ReceiptField,item?:number,value?:string|number)=>active.field===field&&active.item===item?'● Editing':assignments.some(assignment=>assignment.field===field&&assignment.itemIndex===item)?'✓ Assigned':!value||value==='0.00'||value===0?'○ Empty':'⚠ Review';
  const switchCard=(nextCard:number)=>{const next=Math.max(-1,Math.min(last,nextCard));setCard(next);if(next===-1)setActive({field:'restaurant',label:'Restaurant name'});else if(next===last)setActive({field:'serviceCharge',label:'Service tax / charge'});else setActive({field:'itemName',item:next,label:'Food name'});setSelected([])};
  const addItem=()=>{const index=items.length;setItems(current=>[...current,{id:crypto.randomUUID(),name:'',quantity:1,unitPriceCents:0,totalPriceCents:0}]);setCard(index);setActive({field:'itemName',item:index,label:'Food name'});setSelected([])};
  const removeItem=(index:number)=>{if(items.length<=1)return;const nextIndex=Math.min(index,items.length-2);setItems(current=>current.filter((_,itemIndex)=>itemIndex!==index));setAssignments(current=>current.filter(assignment=>assignment.itemIndex!==index).map(assignment=>assignment.itemIndex!==undefined&&assignment.itemIndex>index?{...assignment,itemIndex:assignment.itemIndex-1}:assignment));setCard(nextIndex);setActive({field:'itemName',item:nextIndex,label:'Food name'});setSelected([])};
  const panelDown=(event:React.PointerEvent)=>{swipe.current=event.clientX},panelUp=(event:React.PointerEvent)=>{if(swipe.current!==null&&Math.abs(event.clientX-swipe.current)>55)switchCard(card+(event.clientX<swipe.current?1:-1));swipe.current=null};
  const row=(field:ReceiptField,label:string,value:string,item?:number)=><button className={`summary-field ${active.field===field&&active.item===item?'active':''}`} data-receipt-field={field} data-receipt-label={label} data-receipt-item={item} onClick={()=>activate({field,label,item})}><span>{label}</span><input value={value} onClick={event=>event.stopPropagation()} onChange={event=>item!==undefined?setItem(item,field,event.target.value):field==='restaurant'?setRestaurant(event.target.value):setCharges(current=>({...current,[field]:toCents(event.target.value)}))}/><small>{status(field,item,value)}</small></button>;
  const tokenDrop=(id:string,x:number,y:number)=>{const target=document.elementFromPoint(x,y)?.closest<HTMLElement>('[data-receipt-field]');if(!target)return;const item=target.dataset.receiptItem;assign({field:target.dataset.receiptField as ReceiptField,label:target.dataset.receiptLabel||'',item:item===undefined?undefined:Number(item)},[id])};

  const current=card===-1?<><span className="eyebrow">RESTAURANT</span>{row('restaurant','Restaurant name',restaurant)}</>:card===last?<><span className="eyebrow">CHARGES & TOTAL</span><div className="calculated-row"><span>Food subtotal</span><strong>RM{(calculatedSubtotal/100).toFixed(2)}</strong><small>Auto-calculated</small></div>{CHARGE.map(([field,label])=>row(field,label,(charges[field as keyof typeof charges]/100).toFixed(2)))}<button type="button" className="secondary mapping-add-item" onClick={addItem}><Plus size={16}/> Add item</button></>:<><div className="mapping-item-heading"><span className="eyebrow">ITEM {String(card+1).padStart(2,'0')}</span><button type="button" className="mapping-delete-item" disabled={items.length<=1} onClick={()=>removeItem(card)}><Trash2 size={15}/> Delete item</button></div>{ITEM.map(([field,label])=>row(field,label,itemValue(card,field),card))}</>;

  return <><div className="page-title map-title"><span className="eyebrow">MAP RECEIPT FIELDS</span><h1>Review receipt</h1></div><div ref={workspace} className="mobile-map-workspace"><div className="active-field"><div><small>EDITING</small><strong>{active.item!==undefined?`Item ${String(active.item+1).padStart(2,'0')} · `:''}{active.label}</strong>{selected.length>0&&<span>Selected: {selectedText}</span>}</div>{active.field==='itemName'&&selected.length>0&&<button onClick={()=>assign()}>Confirm</button>}<button type="button" onClick={onClear} aria-label="Clear receipt and upload another photo">Clear</button><button type="button" aria-label="Close receipt review and return home" onClick={onClose}><X size={16}/></button></div><ReceiptViewer imageUrl={imageUrl} imageWidth={imageWidth} imageHeight={imageHeight} tokens={tokens} selected={selected} assigned={used} onTokenTap={tokenTap} onTokenDropAt={tokenDrop}/><div className="current-card" onPointerDown={panelDown} onPointerUp={panelUp}><div className="card-nav"><button disabled={card<=-1} onClick={()=>switchCard(card-1)}><ChevronLeft/></button><strong>{card===-1?'Restaurant':card===last?'Charges & total':`Item ${card+1} of ${items.length}`}</strong><button disabled={card>=last} onClick={()=>switchCard(card+1)}><ChevronRight/></button></div>{current}<label className="auto-advance"><input type="checkbox" checked={auto} onChange={event=>setAuto(event.target.checked)}/> Auto next</label></div></div>
  <section className="mapping-summary"><div className="section-heading"><h2>Summary</h2><span className="muted">{items.length} items</span></div><div className="card"><strong>Restaurant</strong><p>{restaurant||'Not assigned'}</p></div>{items.map((item,index)=><button className="card summary-jump" key={item.id} onClick={()=>{switchCard(index);workspace.current?.scrollIntoView({behavior:'smooth',block:'start'})}}><span><b>ITEM {String(index+1).padStart(2,'0')}</b><strong>{item.name||'Unnamed item'}</strong><small>{item.quantity} × RM{(item.unitPriceCents/100).toFixed(2)} = RM{(item.totalPriceCents/100).toFixed(2)}</small></span><em>{ITEM.every(([field])=>assignments.some(assignment=>assignment.field===field&&assignment.itemIndex===index))?'✓':'⚠'}</em></button>)}<div className="card"><strong>Charges & total</strong><div className="summary-total calculated-total"><span>Food subtotal</span><span>RM{(calculatedSubtotal/100).toFixed(2)}</span></div>{CHARGE.map(([field,label])=><button className="summary-total" key={field} onClick={()=>{switchCard(last);activate({field,label});workspace.current?.scrollIntoView({behavior:'smooth',block:'start'})}}><span>{label}</span><span>RM{(charges[field as keyof typeof charges]/100).toFixed(2)}</span></button>)}<div className="summary-total calculated-total bill-total"><span>Calculated bill total</span><span>RM{(calculatedTotal/100).toFixed(2)}</span></div></div><button className="secondary full" onClick={addItem}><Plus size={16}/> Add item</button></section>
  <button className="primary full" onClick={()=>onConfirm({...initial,restaurant,items,serviceChargeCents:charges.serviceCharge,taxCents:charges.tax,discountCents:charges.discount,roundingCents:charges.rounding,printedSubtotalCents:initial.printedSubtotalCents??null,printedTotalCents:initial.printedTotalCents??null},assignments)}><Check size={18}/> Confirm receipt</button>{onExport&&<button className="text-button export-mappings" onClick={onExport}>Export corrections (developer)</button>}</>;
}
