import {memo,useCallback,useEffect,useMemo,useRef,useState}from'react';
import type{PointerEvent as ReactPointerEvent}from'react';
import type{OcrToken}from'../types';

type DragState={pointerId:number;startX:number;startY:number;ghost:HTMLDivElement|null;over:HTMLElement|null};

const Token=memo(function Token({token,imageWidth,imageHeight,selected,assigned,onTap,onDropAt,debug}:{token:OcrToken;imageWidth:number;imageHeight:number;selected:boolean;assigned:boolean;onTap:(id:string)=>void;onDropAt:(id:string,x:number,y:number)=>void;debug:boolean}){
  const drag=useRef<DragState|null>(null);
  const clearDrag=(drop?:{x:number;y:number})=>{const current=drag.current;if(!current)return;current.over?.classList.remove('drag-over');current.ghost?.remove();drag.current=null;if(drop&&current.ghost)onDropAt(token.id,drop.x,drop.y);};
  const pointerDown=(e:ReactPointerEvent<HTMLButtonElement>)=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,ghost:null,over:null};};
  const pointerMove=(e:ReactPointerEvent<HTMLButtonElement>)=>{const current=drag.current;if(!current||current.pointerId!==e.pointerId)return;if(!current.ghost&&Math.hypot(e.clientX-current.startX,e.clientY-current.startY)>6){const ghost=document.createElement('div');ghost.className='touch-drag-ghost';ghost.textContent=token.text;document.body.appendChild(ghost);current.ghost=ghost;}if(!current.ghost)return;e.preventDefault();current.ghost.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0) translate(-50%,calc(-100% - 12px))`;const next=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-receipt-field]')||null;if(next!==current.over){current.over?.classList.remove('drag-over');next?.classList.add('drag-over');current.over=next;}};
  const pointerUp=(e:ReactPointerEvent<HTMLButtonElement>)=>{const moved=!!drag.current?.ghost;clearDrag(moved?{x:e.clientX,y:e.clientY}:undefined);if(!moved)onTap(token.id);};
  return <button type="button" className={`ocr-box ${selected?'selected':''} ${assigned?'assigned':''} ${token.confidence<.7?'low':''}`} style={{left:`${token.bbox.x/imageWidth*100}%`,top:`${token.bbox.y/imageHeight*100}%`,width:`${token.bbox.width/imageWidth*100}%`,height:`${token.bbox.height/imageHeight*100}%`}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={()=>clearDrag()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onTap(token.id);}}} aria-label={`Receipt text: ${token.text}`} title={`${token.text} · ${Math.round(token.confidence*100)}% · x:${token.bbox.x} y:${token.bbox.y} w:${token.bbox.width} h:${token.bbox.height}`}>{debug&&<span>{token.text} {Math.round(token.confidence*100)}%</span>}</button>;
});

export function ReceiptViewer({imageUrl,imageWidth,imageHeight,tokens,selected,assigned,onTokenTap,onTokenDropAt}:{imageUrl:string;imageWidth:number;imageHeight:number;tokens:OcrToken[];selected:string[];assigned:Set<string>;onTokenTap:(id:string)=>void;onTokenDropAt:(id:string,x:number,y:number)=>void}){
  const layer=useRef<HTMLDivElement>(null),debug=new URLSearchParams(location.search).get('ocrDebug')==='1',[rendered,setRendered]=useState({width:0,height:0});
  useEffect(()=>{if(!debug||!layer.current)return;const observer=new ResizeObserver(([entry])=>setRendered({width:Math.round(entry.contentRect.width),height:Math.round(entry.contentRect.height)}));observer.observe(layer.current);return()=>observer.disconnect();},[debug]);
  const clean=useMemo(()=>tokens.filter((token,index,list)=>token.text.trim()&&token.confidence>=.2&&token.bbox.width<imageWidth*.9&&token.bbox.height<imageHeight*.25&&!list.slice(0,index).some(other=>other.text===token.text&&Math.abs(other.bbox.x-token.bbox.x)<3&&Math.abs(other.bbox.y-token.bbox.y)<3)),[tokens,imageWidth,imageHeight]),tap=useCallback((id:string)=>onTokenTap(id),[onTokenTap]),drop=useCallback((id:string,x:number,y:number)=>onTokenDropAt(id,x,y),[onTokenDropAt]);
  return <div className="receipt-pan receipt-drag-source"><div ref={layer} className="receipt-transform-layer" style={{aspectRatio:`${imageWidth}/${imageHeight}`}}><img draggable={false} src={imageUrl} alt="Your receipt"/>{clean.map(t=><Token key={t.id} token={t} imageWidth={imageWidth} imageHeight={imageHeight} selected={selected.includes(t.id)} assigned={assigned.has(t.id)} onTap={tap} onDropAt={drop} debug={debug}/>)}</div>{debug&&<div className="ocr-coordinate-debug">OCR {imageWidth}×{imageHeight} · Rendered {rendered.width}×{rendered.height} · Scale {(rendered.width/imageWidth||0).toFixed(3)}×{(rendered.height/imageHeight||0).toFixed(3)}</div>}</div>;
}
