/** FastSplit persistence API. Receipt images and OCR never reach this service. */
var HEADERS=['receiptId','sessionId','restaurant','createdAt','expiresAt','subtotalCents','serviceChargeCents','taxCents','discountCents','totalCents','participantCount','receiptDataJson'],RETENTION_MS=72*60*60*1000;
function doGet(){return output_({ok:true,data:{name:'FastSplit',version:'1.1',retentionHours:72}});}
function doPost(e){try{if(!e||!e.postData||e.postData.contents.length>5700000)throw Error('Invalid request.');var r=JSON.parse(e.postData.contents);if(!/^fs_[a-f0-9]{64}$/.test(r.sessionId||''))throw Error('Invalid session.');var l=LockService.getScriptLock();if(!l.tryLock(15000))throw Error('Busy. Please retry.');try{var d;switch(r.action){case'createReceipt':d=createReceipt_(r.sessionId,r.data);break;case'history':d=history_(r.sessionId);break;case'getReceipt':d=getReceipt_(r.sessionId,r.receiptId);break;case'deleteReceipt':d=deleteReceipt_(r.sessionId,r.receiptId);break;default:throw Error('Unknown action.');}return output_({ok:true,data:d});}finally{l.releaseLock();}}catch(x){return output_({ok:false,error:x.message||'Request failed.'});}}
function output_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}
function sheet_(){var id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw Error('Database is not configured.');var s=SpreadsheetApp.openById(id).getSheetByName('Receipts');if(!s)throw Error('Run setupFastSplit first.');return s;}
function setupFastSplit(){var p=PropertiesService.getScriptProperties(),id=p.getProperty('SPREADSHEET_ID'),b=id?SpreadsheetApp.openById(id):SpreadsheetApp.create('FastSplit Database');if(!id)p.setProperty('SPREADSHEET_ID',b.getId());var s=b.getSheetByName('Receipts')||b.insertSheet('Receipts');if(s.getLastRow()===0){s.appendRow(HEADERS);s.setFrozenRows(1);s.getRange(1,1,1,HEADERS.length).setFontWeight('bold').setBackground('#dcecdf');}createCleanupTrigger();}
function createCleanupTrigger(){if(!ScriptApp.getProjectTriggers().some(function(t){return t.getHandlerFunction()==='cleanupExpiredReceipts';}))ScriptApp.newTrigger('cleanupExpiredReceipts').timeBased().everyHours(1).create();}
function rows_(s){return s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,HEADERS.length).getValues();}function live_(r,session){return r[1]===session&&new Date(r[4]).getTime()>Date.now();}
function cleanupExpiredReceipts(){var l=LockService.getScriptLock();l.waitLock(20000);try{var s=sheet_(),a=rows_(s),n=0,now=Date.now();for(var i=a.length-1;i>=0;i--)if(new Date(a[i][4]).getTime()<=now){s.deleteRow(i+2);n++;}return n;}finally{l.releaseLock();}}
function history_(session){return rows_(sheet_()).filter(function(r){return live_(r,session);}).map(function(r){return JSON.parse(r[11]);}).sort(function(a,b){return Date.parse(b.createdAt)-Date.parse(a.createdAt);});}
function getReceipt_(session,id){var r=rows_(sheet_()).find(function(x){return x[0]===id&&live_(x,session);});if(!r)throw Error('Receipt not found or expired.');return JSON.parse(r[11]);}
function deleteReceipt_(session,id){var s=sheet_(),a=rows_(s),i=a.findIndex(function(x){return x[0]===id&&live_(x,session);});if(i<0)throw Error('Receipt not found or expired.');s.deleteRow(i+2);return true;}
function text_(v,max){if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('Invalid text field.');return v.trim();}function int_(v,max){if(!Number.isSafeInteger(v)||v<0||v>max)throw Error('Invalid numeric field.');return v;}function list_(v,min,max){if(!Array.isArray(v)||v.length<min||v.length>max)throw Error('Invalid list.');return v;}function unique_(a){if(new Set(a).size!==a.length)throw Error('Duplicate IDs or names.');}
function allocate_(total,w){var sum=w.reduce(function(a,b){return a+b;},0);if(!sum){if(total)throw Error('Cannot allocate without food.');return w.map(function(){return 0;});}var out=w.map(function(x){return Number(BigInt(total)*BigInt(x)/BigInt(sum));}),order=w.map(function(x,i){return{i:i,r:BigInt(total)*BigInt(x)%BigInt(sum)};}).sort(function(a,b){return a.r===b.r?a.i-b.i:a.r>b.r?-1:1;}),left=total-out.reduce(function(a,b){return a+b;},0);for(var i=0;i<order.length&&left;i++,left--)out[order[i].i]++;return out;}
function validateBill_(d){if(!d||typeof d!=='object')throw Error('Invalid receipt.');var restaurant=text_(d.restaurant,100),requestId=text_(d.requestId,80);if(!/^[a-f0-9-]{36}$/.test(requestId))throw Error('Invalid request ID.');var people=list_(d.participants,1,30).map(function(p){return{id:text_(p.id,80),name:text_(p.name,60)};});unique_(people.map(function(p){return p.id;}));unique_(people.map(function(p){return p.name.toLowerCase();}));var items=list_(d.items,1,50).map(function(x){var q=int_(x.quantity,50);if(!q)throw Error('Quantity must be positive.');var price=int_(x.unitPriceCents,10000000);return{id:text_(x.id,80),name:text_(x.name,100),quantity:q,unitPriceCents:price,totalPriceCents:q*price};});unique_(items.map(function(x){return x.id;}));var sub=items.reduce(function(s,x){return s+x.totalPriceCents;},0);if(!sub)throw Error('Food subtotal must be positive.');var units=list_(d.itemUnits,1,500);if(units.length!==items.reduce(function(s,x){return s+x.quantity;},0))throw Error('Item quantities do not match assignments.');unique_(units.map(function(u){return u.id;}));var canonical=[];items.forEach(function(x){for(var n=0;n<x.quantity;n++){var id=x.id+':'+n,u=units.find(function(v){return v.id===id;});if(!u||u.itemId!==x.id||u.priceCents!==x.unitPriceCents)throw Error('Invalid item unit.');var ids=list_(u.participantIds,x.unitPriceCents?1:0,people.length);unique_(ids);if(ids.some(function(pid){return !people.some(function(p){return p.id===pid;});}))throw Error('Unknown participant.');canonical.push({id:id,itemId:x.id,name:x.quantity>1?x.name+' #'+(n+1):x.name,priceCents:x.unitPriceCents,participantIds:ids});}});var service=int_(d.serviceChargeCents,100000000),tax=int_(d.taxCents,100000000),discount=int_(d.discountCents,sub),food=people.map(function(){return 0;});canonical.forEach(function(u){var shares=allocate_(u.priceCents,people.map(function(p){return u.participantIds.indexOf(p.id)>=0?1:0;}));food=food.map(function(v,i){return v+shares[i];});});var ss=allocate_(service,food),tt=allocate_(tax,food),dd=allocate_(discount,food),settlements=people.map(function(p,i){return{participantId:p.id,foodSubtotalCents:food[i],serviceChargeCents:ss[i],taxCents:tt[i],discountCents:dd[i],finalTotalCents:food[i]+ss[i]+tt[i]-dd[i]};});return{requestId:requestId,restaurant:restaurant,participants:people,items:items,itemUnits:canonical,subtotalCents:sub,serviceChargeCents:service,taxCents:tax,discountCents:discount,totalCents:sub+service+tax-discount,settlements:settlements};}
function createReceipt_(session,d){var b=validateBill_(d),s=sheet_(),a=rows_(s),old=a.find(function(r){return live_(r,session)&&JSON.parse(r[11]).requestId===b.requestId;});if(old)return JSON.parse(old[11]);if(a.filter(function(r){return live_(r,session);}).length>=100)throw Error('Maximum 100 receipts per session in 72 hours.');var now=Date.now();b.id=Utilities.getUuid();b.sessionId=session;b.createdAt=new Date(now).toISOString();b.expiresAt=new Date(now+RETENTION_MS).toISOString();var json=JSON.stringify(b);if(json.length>45000)throw Error('Receipt is too large. Please use fewer items.');s.appendRow([b.id,session,/^[=+@\-]/.test(b.restaurant)?"'"+b.restaurant:b.restaurant,b.createdAt,b.expiresAt,b.subtotalCents,b.serviceChargeCents,b.taxCents,b.discountCents,b.totalCents,b.participants.length,json]);return b;}
