import { useEffect, useRef, useState } from 'react';
import type { Bill, ReceiptItem } from './types';
import { ArrowRight, Camera, Upload, PenLine, ReceiptText, History, Plus, Trash2, Check, ChevronLeft, Users, ShieldCheck, Share2, Clock, X, Utensils, LoaderCircle } from 'lucide-react';
import { calculateItemShares, calculateSettlement, cents, money, totals, validateBillTotal } from './utils/billCalculator';
import { getSessionId } from './services/sessionService';
import { api, apiUrl } from './services/api';
import { demoReceipt, scanReceipt, validateReceiptImage } from './services/receiptScanner';

const uuid = () => crypto.randomUUID();
const newItem = (): ReceiptItem => ({id:uuid(),name:'',quantity:1,unitPriceCents:0,totalPriceCents:0});
function fresh(): Bill { return {id:'',requestId:uuid(),sessionId:getSessionId(),restaurant:'',createdAt:'',expiresAt:'',participants:[],items:[newItem()],itemUnits:[],subtotalCents:0,serviceChargeCents:0,taxCents:0,discountCents:0,totalCents:0,settlements:[]}; }
function loadDraft(): Bill | null { try { const raw=localStorage.getItem('fastsplit-draft'); if (!raw) return null; const parsed=JSON.parse(raw); if (Date.now()-parsed.savedAt>72*3600000) {localStorage.removeItem('fastsplit-draft');return null;} return parsed.bill; } catch { return null; } }
function Amount({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}) {
  const [text,setText]=useState((value/100).toFixed(2));
  useEffect(()=>setText((value/100).toFixed(2)),[value]);
  return <label>{label}<span className="amount-input"><input aria-label={label} inputMode="decimal" value={text} required pattern="[0-9]+(\.[0-9]{1,2})?" onChange={e=>{setText(e.target.value);try{onChange(cents(e.target.value));}catch{/* Native validity blocks continuation. */}}}/></span></label>;
}
function expiry(value:string,now:number) { const hours=Math.max(0,Math.ceil((Date.parse(value)-now)/3600000)); return hours>=24 ? `${Math.floor(hours/24)}d ${hours%24}h` : `${hours}h`; }
export default function App() {
  const [route,setRoute]=useState(location.hash.slice(1)||'/');
  const [draft,setDraft]=useState<Bill|null>(loadDraft);
  const [bill,setBill]=useState<Bill>(()=>loadDraft()||fresh());
  const [records,setRecords]=useState<Bill[]>([]), [detail,setDetail]=useState<Bill|null>(null);
  const [error,setError]=useState(''),[historyError,setHistoryError]=useState(''),[notice,setNotice]=useState('');
  const [busy,setBusy]=useState(''),[loadingHistory,setLoadingHistory]=useState(false),[saved,setSaved]=useState(false);
  const [deleteId,setDeleteId]=useState<string|null>(null),[person,setPerson]=useState('');
  const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[now,setNow]=useState(Date.now());
  const upload=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),inFlight=useRef(false);
  function go(path:string) {setError('');setNotice('');location.hash=path;setRoute(path);window.scrollTo(0,0);}
  useEffect(()=>{const onHash=()=>{setRoute(location.hash.slice(1)||'/');setError('');};window.addEventListener('hashchange',onHash);const timer=setInterval(()=>setNow(Date.now()),30000);return()=>{window.removeEventListener('hashchange',onHash);clearInterval(timer);};},[]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  useEffect(()=>{if(bill.restaurant||bill.items.some(i=>i.name)){try{if(!saved){localStorage.setItem('fastsplit-draft',JSON.stringify({bill,savedAt:Date.now()}));setDraft(bill);}}catch{setNotice('Device storage is unavailable. Keep this page open until your receipt is saved.');}}},[bill,saved]);
  async function loadHistory(){setLoadingHistory(true);setHistoryError('');try{setRecords(await api.history());}catch(e){setHistoryError((e as Error).message);}finally{setLoadingHistory(false);}}
  useEffect(()=>{if(route==='/'||route==='/history')void loadHistory(); if(route.startsWith('/history/')){setDetail(null);setBusy('Loading receipt…');api.get(route.split('/')[2]).then(setDetail).catch(e=>setError(e.message)).finally(()=>setBusy(''));}},[route]);
  async function run(label:string,fn:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(label);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{inFlight.current=false;setBusy('');}}
  function start(){setSaved(false);setBill(fresh());setFile(null);go('/review');}
  function choose(f:File|undefined){if(!f)return;try{validateReceiptImage(f);}catch(e){setError((e as Error).message);return;}setFile(f);go('/scan');}
  function update(patch:Partial<Bill>){setSaved(false);setBill(b=>totals({...b,...patch,requestId:uuid()}));}
  function patchItem(id:string,patch:Partial<ReceiptItem>){setSaved(false);setBill(b=>totals({...b,requestId:uuid(),items:b.items.map(i=>i.id===id?{...i,...patch}:i)}));}
  function prepareUnits(){if(!bill.items.length||!bill.restaurant.trim()||bill.items.some(i=>!i.name.trim()||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>50)||bill.subtotalCents<=0||bill.discountCents>bill.subtotalCents){setError('Add a restaurant and valid items. Food subtotal must be positive; discount cannot exceed it.');return;}update({itemUnits:bill.items.flatMap(i=>Array.from({length:i.quantity},(_,n)=>{const id=`${i.id}:${n}`;return {id,itemId:i.id,name:i.quantity>1?`${i.name} #${n+1}`:i.name,priceCents:i.unitPriceCents,participantIds:bill.itemUnits.find(u=>u.id===id)?.participantIds||[]};}))});go('/people');}
  function addPerson(){const name=person.trim();if(!name)return;if(bill.participants.some(p=>p.name.toLowerCase()===name.toLowerCase())){setError('Use a different name so everyone is easy to identify.');return;}update({participants:[...bill.participants,{id:uuid(),name}]});setPerson('');setError('');}
  async function finalize(){await run('Saving receipt…',async()=>{const next={...bill,settlements:calculateSettlement(bill)};if(!validateBillTotal(next))throw new Error('Bill total does not match. Please review your items.');setBill(next);go('/summary');const result=await api.create(next);setSaved(true);setBill(result);localStorage.removeItem('fastsplit-draft');setDraft(null);});}
  async function share(b:Bill){const text=`🍽 FastSplit\n${b.restaurant}\n\n${b.settlements.map(s=>`${b.participants.find(p=>p.id===s.participantId)?.name} — ${money(s.finalTotalCents)}`).join('\n')}\n\nTotal: ${money(b.totalCents)}\nDon’t split equally. Pay for what you ate.`;await run('Preparing result…',async()=>{try{if(navigator.share){await navigator.share({title:'FastSplit',text});return;}}catch(e){if((e as Error).name==='AbortError')return;}await navigator.clipboard.writeText(text);setNotice('Result copied. Paste it into your group chat.');});}
  const unassigned=bill.itemUnits.filter(u=>u.priceCents>0&&!u.participantIds.length).length;
  const currentRecords=records.filter(r=>Date.parse(r.expiresAt)>now);
  const isFlow=['/review','/people','/assign','/summary','/scan'].includes(route);
  function historyCards(limit?:number){return <>{loadingHistory?<p className="muted">Loading history…</p>:historyError?<div className="empty"><p>{historyError}</p>{apiUrl&&<button className="text-button" onClick={loadHistory}>Try again</button>}</div>:currentRecords.length===0?<div className="empty"><ReceiptText size={30}/><h3>A fresh start for your next meal</h3><p>Your completed bills will appear here.</p></div>:currentRecords.slice(0,limit).map(r=><article className="history-card" key={r.id}><div className="restaurant-icon"><Utensils size={22}/></div><div className="history-info"><h3>{r.restaurant}</h3><p>{new Date(r.createdAt).toLocaleString('en-MY',{dateStyle:'medium',timeStyle:'short'})} · {r.participants.length} people</p><small><Clock size={12}/> Expires in {expiry(r.expiresAt,now)}</small></div><div className="history-actions"><strong>{money(r.totalCents)}</strong><button className="text-button" onClick={()=>go('/history/'+r.id)}>View receipt</button><button aria-label={`Delete ${r.restaurant}`} className="icon-button danger" onClick={()=>setDeleteId(r.id)}><Trash2 size={16}/></button></div></article>)}</>;}
  function summary(b:Bill,historical=false){return <><div className="page-title"><span className="eyebrow">{historical?'PAST MEAL':'ALL SQUARE'}</span><h1>{historical?'Your receipt':'Good food. Fair split.'}</h1><p>{b.restaurant}{historical&&` · ${new Date(b.createdAt).toLocaleString()}`}</p></div>{!historical&&<div className={`save-status ${saved?'success':''}`} role="status">{saved?<><Check size={18}/> Receipt saved to History</>:<><Clock size={18}/> {busy||'Receipt not saved yet. Your draft is kept on this device.'}</>}{!saved&&!busy&&<button onClick={finalize}>Retry save</button>}</div>}<section className="total-banner"><span>Everyone’s share, sorted.</span><strong>{money(b.totalCents)}</strong><small>{b.participants.length} people · {b.items.length} items</small></section>{b.settlements.map(s=><details className="settlement card" key={s.participantId}><summary><span className="avatar">{b.participants.find(p=>p.id===s.participantId)?.name.slice(0,1)}</span><strong>{b.participants.find(p=>p.id===s.participantId)?.name}</strong><b>{money(s.finalTotalCents)}</b></summary><div className="breakdown">{b.itemUnits.filter(u=>u.participantIds.includes(s.participantId)).map(u=><div key={u.id}><span>{u.name}{u.participantIds.length>1&&` · shared by ${u.participantIds.length}`}</span><span>{money(calculateItemShares(u,b.participants)[b.participants.findIndex(p=>p.id===s.participantId)])}</span></div>)}<hr/><div><span>Food subtotal</span><span>{money(s.foodSubtotalCents)}</span></div><div><span>Service charge</span><span>{money(s.serviceChargeCents)}</span></div><div><span>Tax / SST</span><span>{money(s.taxCents)}</span></div><div><span>Discount</span><span>−{money(s.discountCents)}</span></div></div></details>)}<div className="card breakdown"><div><span>Bill total</span><strong>{money(b.totalCents)}</strong></div><div><span>Allocated</span><strong>{money(b.settlements.reduce((a,s)=>a+s.finalTotalCents,0))}</strong></div><div className="green"><span><Check size={15}/> Difference</span><strong>{money(b.totalCents-b.settlements.reduce((a,s)=>a+s.finalTotalCents,0))}</strong></div></div><button className="primary full" disabled={!!busy} onClick={()=>share(b)}><Share2 size={18}/> Share result</button><p className="retention"><Clock size={14}/> History is automatically deleted after 72 hours.</p></>;}
  return <><header className="topbar"><a className="brand" href="#/"><span className="brand-mark">f<span>·</span></span>FastSplit<span className="brand-dot">®</span></a><nav><a className={route==='/'?'active':''} href="#/">Split a bill</a><a className={route.startsWith('/history')?'active':''} href="#/history"><History size={16}/> History</a></nav></header><main>
    {error&&<div className="alert" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}{notice&&<div className="save-status" role="status">{notice}</div>}
    {isFlow&&<><button className="back text-button" disabled={!!busy} onClick={()=>go(route==='/people'?'/review':route==='/assign'?'/people':'/')}><ChevronLeft size={16}/> Back</button><div className="steps">{['Receipt','People','Split','Summary'].map((s,i)=><span key={s} className={['/review','/people','/assign','/summary'][i]===route?'current':''}><b>{i+1}</b>{s}</span>)}</div></>}
    {route==='/'&&<><section className="hero"><span className="eyebrow"><span className="live-dot"/> LESS MATH. MORE GOOD TIMES.</span><h1>Don’t split equally.<br/><span>Pay for what<br className="mobile-break"/> you ate.</span></h1><p>From the first bite to the last cent.<br/>A fair share for everyone at the table.</p><div className="hero-actions"><button className="primary" onClick={()=>camera.current?.click()}><Camera size={20}/> Scan receipt <ArrowRight size={18}/></button><button className="secondary" onClick={()=>upload.current?.click()}><Upload size={18}/> Upload receipt</button><button className="manual" onClick={start}><PenLine size={16}/> Enter manually <ArrowRight size={16}/></button></div><div className="hero-receipt" aria-hidden="true"><div className="receipt-top"><Utensils size={18}/><span>GOOD FOOD CLUB</span></div><p>One table. Your share.</p><div><span>Chicken ramen</span><b>18.00</b></div><div><span>Salmon sushi × 2</span><b>16.00</b></div><div><span>Iced green tea × 3</span><b>9.00</b></div><hr/><div><span>With service & tax</span><b>49.88</b></div><div className="receipt-people"><span>J</span><span>A</span><span>M</span><small>Split fairly ✓</small></div><div className="fair-stamp"><Check size={18}/> Every cent, accounted for.</div></div></section><div className="trust-strip"><span><ShieldCheck size={17}/> No sign-up needed</span><span><Users size={17}/> Shared food, sorted</span><span><Check size={17}/> Accurate to the cent</span></div>{draft&&<div className="resume card"><div><strong>You have an unfinished bill</strong><p>{draft.restaurant||'Your next meal'}</p></div><button className="text-button" onClick={()=>{setBill(draft);setSaved(false);go('/review');}}>Continue <ArrowRight size={16}/></button></div>}<section className="how"><div><span>01</span><h3>Bring the bill</h3><p>Scan, upload, or type it in.</p></div><div><span>02</span><h3>Pick your people</h3><p>Choose who ate what.</p></div><div><span>03</span><h3>Make it fair</h3><p>Share the totals. You’re done.</p></div></section><section className="history-section"><div className="section-heading"><h2>Recent bills</h2><a href="#/history">View all <ArrowRight size={15}/></a></div><p className="muted">Good memories last. Receipt history stays for 3 days.</p>{historyCards(3)}</section><button className="text-button demo" onClick={()=>{setSaved(false);setBill(totals({...fresh(),...demoReceipt()}));go('/review');}}>Just looking? Try a demo receipt <ArrowRight size={15}/></button></>}
    {route==='/scan'&&<><div className="page-title"><span className="eyebrow">BRING THE BILL</span><h1>A clear photo goes a long way.</h1><p>Keep the whole receipt in frame, with readable prices.</p></div><div className="card scan-preview">{preview?<img src={preview} alt="Receipt preview"/>:<p>Select a receipt image to get started.</p>}</div><button className="secondary full" onClick={()=>upload.current?.click()}>Replace image</button><button className="primary full" disabled={!file||!!busy} onClick={()=>run('Scanning receipt…',async()=>{const receipt=await scanReceipt(file!);setSaved(false);setBill(totals({...fresh(),...receipt}));setFile(null);go('/review');setNotice(receipt.scanWarning||'Scan complete. Check the quantities and prices against your receipt.');})}>{busy||'Confirm & scan'}<ArrowRight size={18}/></button><p className="retention">Images are processed only, never stored in History. OCR requires a configured provider.</p><button className="text-button" onClick={start}>Enter the receipt manually instead</button></>}
    {route==='/review'&&<><div className="page-title"><span className="eyebrow">CHECK THE DETAILS</span><h1>Let’s get the bill right.</h1><p>Review each item. We’ll take care of the maths.</p></div><form onSubmit={e=>{e.preventDefault();prepareUnits();}}><div className="card"><label>Restaurant<input required maxLength={100} placeholder="Where did you eat?" value={bill.restaurant} onChange={e=>update({restaurant:e.target.value})}/></label></div><div className="section-heading"><h2>On the table</h2><span className="muted">{bill.items.length} items</span></div>{bill.items.map((item,i)=><div className="card item-editor" key={item.id}><div className="item-heading"><span className="eyebrow">ITEM {String(i+1).padStart(2,'0')}</span><button type="button" className="icon-button danger" aria-label={`Delete item ${i+1}`} onClick={()=>update({items:bill.items.filter(x=>x.id!==item.id)})}><Trash2 size={17}/></button></div><label>Item name<input required maxLength={100} placeholder="e.g. Chicken ramen" value={item.name} onChange={e=>patchItem(item.id,{name:e.target.value})}/></label><div className="input-row"><label>Quantity<input required type="number" min="1" max="50" value={item.quantity||''} onChange={e=>patchItem(item.id,{quantity:Number(e.target.value)})}/></label><Amount label={`Unit price · item ${i+1}`} value={item.unitPriceCents} onChange={n=>patchItem(item.id,{unitPriceCents:n})}/><div className="line-total"><span>Item total</span><strong>{money(item.totalPriceCents)}</strong></div></div></div>)}<button type="button" className="secondary full" disabled={bill.items.length>=50} onClick={()=>update({items:[...bill.items,newItem()]})}><Plus size={17}/> Add item</button><div className="card charges"><div className="section-heading"><h3>A little extra</h3><small>Enter amounts, not percentages</small></div><Amount label="Service charge" value={bill.serviceChargeCents} onChange={n=>update({serviceChargeCents:n})}/><Amount label="Tax / SST" value={bill.taxCents} onChange={n=>update({taxCents:n})}/><Amount label="Discount" value={bill.discountCents} onChange={n=>update({discountCents:n})}/><div className="breakdown"><div><span>Food subtotal</span><span>{money(bill.subtotalCents)}</span></div><div className="bill-total"><strong>Bill total</strong><strong>{money(bill.totalCents)}</strong></div></div></div><button className="primary full">Continue to people <ArrowRight size={18}/></button></form></>}
    {route==='/people'&&<><div className="page-title"><span className="eyebrow">YOUR TABLE</span><h1>Who’s eating?</h1><p>Add everyone who’s sharing this meal.</p></div><form className="add-person" onSubmit={e=>{e.preventDefault();addPerson();}}><input aria-label="Friend’s name" placeholder="Friend’s name" maxLength={60} value={person} onChange={e=>setPerson(e.target.value)}/><button className="primary" disabled={bill.participants.length>=30}><Plus size={18}/> Add</button></form><div className="card">{bill.participants.length===0?<div className="empty"><Users size={32}/><p>A good meal starts with good company.</p></div>:bill.participants.map((p,i)=><div className="person-row" key={p.id}><span className={`avatar color-${i%4}`}>{p.name.slice(0,1)}</span><input aria-label={`Participant ${i+1}`} maxLength={60} value={p.name} onChange={e=>update({participants:bill.participants.map(x=>x.id===p.id?{...x,name:e.target.value}:x)})}/><button className="icon-button danger" aria-label={`Remove ${p.name}`} onClick={()=>update({participants:bill.participants.filter(x=>x.id!==p.id),itemUnits:bill.itemUnits.map(u=>({...u,participantIds:u.participantIds.filter(id=>id!==p.id)}))})}><X size={18}/></button></div>)}</div><button className="primary full" disabled={!bill.participants.length||bill.participants.some(p=>!p.name.trim())||new Set(bill.participants.map(p=>p.name.trim().toLowerCase())).size!==bill.participants.length} onClick={()=>go('/assign')}>Choose who ate what <ArrowRight size={18}/></button></>}
    {route==='/assign'&&<><div className="page-title"><span className="eyebrow">A SHARE FOR EVERYONE</span><h1>Who had what?</h1><p>Tap a name to assign. Tap a few to share.</p></div><div className="assignment-status">{unassigned?<><Clock size={17}/>{unassigned} items still need to be assigned</>:<><Check size={17}/> All items assigned. Ready to split!</>}</div>{bill.itemUnits.map(u=><div className={`card assignment ${u.priceCents&&!u.participantIds.length?'unassigned':''}`} key={u.id}><div className="section-heading"><h3>{u.name}</h3><strong>{money(u.priceCents)}</strong></div><div className="chips">{bill.participants.map(p=><button className={u.participantIds.includes(p.id)?'chip selected':'chip'} key={p.id} aria-pressed={u.participantIds.includes(p.id)} onClick={()=>update({itemUnits:bill.itemUnits.map(x=>x.id===u.id?{...x,participantIds:x.participantIds.includes(p.id)?x.participantIds.filter(id=>id!==p.id):[...x.participantIds,p.id]}:x)})}>{u.participantIds.includes(p.id)&&<Check size={14}/>} {p.name}</button>)}<button className="text-button" onClick={()=>update({itemUnits:bill.itemUnits.map(x=>x.id===u.id?{...x,participantIds:bill.participants.map(p=>p.id)}:x)})}>Everyone</button></div>{u.participantIds.length>0&&<small className="muted">{u.participantIds.length===1?'One person’s pick':`Shared by ${u.participantIds.length} · about ${money(Math.floor(u.priceCents/u.participantIds.length))} each (extra cents assigned fairly)`}</small>}</div>)}<p className="retention">Service charge, SST, and discounts follow each person’s food share.</p><button className="primary full" disabled={unassigned>0||!bill.participants.length||!bill.itemUnits.length||!!busy} onClick={finalize}>{busy||'Calculate & save'}<ArrowRight size={18}/></button></>}
    {route==='/summary'&&summary(bill)}
    {route==='/history'&&<><div className="page-title"><span className="eyebrow">YOUR SHARED MEALS</span><h1>Receipt history.</h1><p>All settled, all in one place.</p></div><div className="save-status"><Clock size={18}/> Receipts are automatically deleted after 3 days (72 hours).</div>{historyCards()}<button className="secondary full" onClick={loadHistory} disabled={loadingHistory}>Refresh history</button></>}
    {route.startsWith('/history/')&&<><button className="back text-button" onClick={()=>go('/history')}><ChevronLeft size={16}/> Back to history</button>{busy?<p>{busy}</p>:detail&&Date.parse(detail.expiresAt)>now?summary(detail,true):<p className="empty">This receipt is unavailable or has expired.</p>}</>}
    {!['/','/scan','/review','/people','/assign','/summary','/history'].includes(route)&&!route.startsWith('/history/')&&<div className="empty"><h1>Page not found</h1><a href="#/">Back to FastSplit</a></div>}
    <input ref={upload} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.target.value='';}}/><input ref={camera} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>{choose(e.target.files?.[0]);e.target.value='';}}/>
  </main><footer><span className="brand small">FastSplit<span className="green">·</span></span><span>Made for meals, not maths.</span><small>No account needed</small></footer>{busy&&route!=='/assign'&&route!=='/summary'&&<div className="busy-toast" role="status"><LoaderCircle size={17} className="spin"/>{busy}</div>}{deleteId&&<div className="modal-overlay"><section className="modal card" role="dialog" aria-modal="true" aria-labelledby="delete-title"><div className="restaurant-icon"><Trash2/></div><h2 id="delete-title">Delete this receipt?</h2><p>This action cannot be undone. It will be removed from your history.</p><div className="modal-actions"><button autoFocus className="secondary" disabled={!!busy} onClick={()=>setDeleteId(null)}>Cancel</button><button className="delete-button" disabled={!!busy} onClick={()=>run('Deleting receipt…',async()=>{await api.delete(deleteId);setDeleteId(null);await loadHistory();})}>{busy||'Delete receipt'}</button></div></section></div>}</>;
}
